#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON1                               100
#define IDR_MENU1                               1001
#define IDM_FILE1                               1002
#define IDM_PROJECT1                            1003
#define IDD_DIALOG_CONVERTER                    2015
#define IDD_DIALOG_CALCULATOR                   2016
#define IDD_DIALOG_NOTES                        2017
#define IDD_DIALOG_NIVELATOR                    2018
#define IDD_DIALOG_POSITIONER                   2019
#define IDD_DIALOG_POINTS                       2020
#define ID_CALCULATOR_OK                        4001
#define ID_CHS                                  5008
#define ID_CHO                                  5009
#define ID_OPTION_DT                            5011
#define ID_OPTION_NT                            5013
#define ID_CONVERTER_OK                         5014
#define ID_CONVERTER_CANCEL                     5015
#define ID_CONVERTER_ADD                        5016
#define ID_CONVERTER_BAR                        5017
#define ID_NOTAS_PIZARRA                        6001
#define ID_NOTAS_SALIRASISTENTE                 6002
#define ID_NOTAS_SAVE                           6003
#define ID_NOTAS_BORRARPIZARRA                  6004
#define IDD_DIALOG1                             6969
#define ID_NIVELADOR_SALIR                      7001
#define ID_PERFIL_SAVE                          7002
#define ID_NOTAS_NIVELADOR                      7003
#define ID_NIVELAR                              7004
#define ID_POSITIONER_CANCEL                    8001
#define ID_POSITIONER_OK                        8002
#define ID_POSITIONER_STATIC                    8003
#define ID_POSITIONER_DYNAMIC                   8004
#define ID_POSITIONER_ABSOLUTE                  8005
#define ID_POSITIONER_DIFFERENTIAL              8006
#define ID_CALCULATOR_CANCEL                    40000
#define ID_EQUAL                                40001
#define ID_STATIC_TEXT                          40002
#define ID_EDIT_CONTROL                         40003
#define ID_PLUS                                 40004
#define ID_MINUS                                40005
#define ID_OPEN                                 40006
#define ID_CLOSE                                40007
#define ID_DELETE                               40008
#define ID_CLEAN                                40009
#define ID_ONE                                  40010
#define ID_TWO                                  40011
#define ID_THREE                                40012
#define ID_FOUR                                 40013
#define ID_FIVE                                 40014
#define ID_SIX                                  40015
#define ID_SEVEN                                40016
#define ID_NINE                                 40017
#define ID_EIGTH                                40018
#define ID_ZERO                                 40019
